[package]
name          = "kiibohd-core"
version       = "0.1.0"
authors       = ["Jacob Alexander <haata@kiibohd.com>"]
license       = "MIT OR Apache-2.0"
edition       = "2018"


[lib]
name = "kiibohd_core"


[features]
default = [
  "kiibohd-hall-effect",
  "kiibohd-hid-io",
  "kiibohd-keyscanning",
]

# The std option is used for cargo test only
std = []

# Used when compiling as a static library
lib = []


[workspace]
members = [
  "kiibohd-hall-effect",
  "kiibohd-hid-io",
  "kiibohd-keyscanning",
]


[dependencies]
c_utf8              = { version = "^0.1", default-features = false }
cstr_core           = { version = "^0.2", default-features = false }
heapless            = { version = "^0.6" }
kiibohd-hid-io      = { path = "kiibohd-hid-io", optional = true }
kiibohd-hall-effect = { path = "kiibohd-hall-effect", optional = true }
kiibohd-keyscanning = { path = "kiibohd-keyscanning", optional = true }
pkg-version         = { version = "^1.0" }
typenum             = { version = "^1.12", features = ["no_std"] }
